name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello github action
        run: echo "Hello this is first worflow in github action"
      - name: Bye github action
        run: echo "Bye github action"
      - name: Job failed intentionally
        run: exit 1
