# Sequentially implementing jobs
# By default, jobs are implemented in parallel

name: Multiple Job Test

on:
  workflow_run:
    workflows: [Validate files]
    types:
      - completed

jobs:
  validate-html:
    # Checking existence of HTML
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4

      - name: Validate HTML file
        run: test -f index.html

  validate-js:
    # Checking existence of JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4

      - name: Validate JS file
        run: test -f index.js

  validate-code:
    # This job runs only after both validation jobs complete
    needs: [validate-html, validate-js]
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4

      - name: Check JavaScript syntax
        run: node --check index.js

      - name: Validate HTML
        run: npx htmlhint index.html
